require:
  - rubocop-rspec
  - rubocop-rspec_rails

plugins:
  - rubocop-rails
  - rubocop-capybara
  - rubocop-factory_bot

AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'node_modules/**/*'
    - 'db/schema.rb'
    - 'tmp/**/*'
    - 'spec/dummy/**/*'

# Metrics
Metrics/AbcSize:
  Max: 65
  Exclude:
    - 'spec/**/*'
    - 'app/controllers/**/*'
    - 'lib/generators/**/*'
    - 'lib/pg_sql_triggers/testing/**/*'

Metrics/BlockLength:
  Max: 50
  Exclude:
    - 'spec/**/*'
    - 'config/routes.rb'
    - '*.gemspec'
    - 'lib/tasks/**/*'

Metrics/ClassLength:
  Max: 200
  Exclude:
    - 'spec/**/*'

Metrics/CyclomaticComplexity:
  Max: 18
  Exclude:
    - 'app/controllers/**/*'
    - 'lib/pg_sql_triggers/testing/**/*'

Metrics/MethodLength:
  Max: 55
  Exclude:
    - 'spec/**/*'
    - 'app/controllers/**/*'
    - 'lib/generators/**/*'
    - 'lib/pg_sql_triggers/testing/**/*'

Metrics/PerceivedComplexity:
  Max: 15
  Exclude:
    - 'app/controllers/**/*'
    - 'lib/pg_sql_triggers/testing/**/*'

# Style
Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/FrozenStringLiteralComment:
  Enabled: true

# Layout
Layout/LineLength:
  Max: 120
  Exclude:
    - 'spec/**/*'

# Gemspec
Gemspec/DevelopmentDependencies:
  Enabled: false

# Rails
Rails:
  Enabled: true

Rails/I18nLocaleTexts:
  Enabled: false

Rails/StrongParametersExpect:
  Enabled: false

# RSpec
RSpec/ExampleLength:
  Max: 10
  Exclude:
    - 'spec/**/*_spec.rb'

RSpec/FilePath:
  Enabled: false

RSpec/InstanceVariable:
  Enabled: false

RSpec/MessageChain:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

RSpec/MultipleDescribes:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 10

RSpec/SpecFilePathFormat:
  Enabled: false

RSpec/AnyInstance:
  Enabled: false

RSpec/LetSetup:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

RSpec/VerifiedDoubles:
  Enabled: false

RSpec/RepeatedExample:
  Enabled: false

# Capybara
Capybara/RSpec/PredicateMatcher:
  Enabled: false
