require:
  - rubocop-rspec

plugins:
  - rubocop-rails

AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
  Exclude:
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'node_modules/**/*'
    - 'db/schema.rb'
    - 'tmp/**/*'
    - 'spec/dummy/**/*'

# Metrics
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'config/routes.rb'
    - '*.gemspec'

Metrics/MethodLength:
  Max: 15
  Exclude:
    - 'spec/**/*'

# Style
Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/FrozenStringLiteralComment:
  Enabled: true

# Layout
Layout/LineLength:
  Max: 120
  Exclude:
    - 'spec/**/*'

# Rails
Rails:
  Enabled: true

# RSpec
RSpec/ExampleLength:
  Max: 10
  Exclude:
    - 'spec/**/*_spec.rb'

RSpec/MultipleExpectations:
  Max: 5
